name = "hnr22"
type = "webpack"
account_id = "85fad368ff87a470ab16c64b0197fce6"
workers_dev = true
compatibility_date = "2022-01-07"
kv_namespaces = [
    { binding = "HNR22_KV", id = "REDACTED", preview_id = "REDACTED" }
]

[vars]
BOT_TOKEN="REDACTED"
